### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by f3l1x** [contributte/nusoap#27]
Hi guys! 

I want to make things clear and set some expections to this library.  Let's make some updates and plan for v1.0.0.

All changes gonna be in **develop** branch to keep things working in master branch.

Roadmap:

- [ ] split nusoap.php into 1-class-1-file
- [ ] introduce new namespace (maybe `Nusoap/*`?)
  - [ ] change internal usage
- [ ] reformat all classes (I'm using PhpStorm)
- [ ] write working example
- [x] write some unit tests
- [x] setup QA
  - [x] Travis CI - test 5.6, 7.0, 7.1, 7.2
  - [ ] codesniffer

I would be happy if some wanna share effort on this library and help me do all this stuff.

Thanks.

**Comment by evilangelmd** [comment]
i'll try to help you in this battle.. i already started to work in this direction and i think a lot of code that was written back in 2010 is deprecated now... i think we will need to reformat a lot of code..  But we can succeed this together :)

**Comment by f3l1x** [comment]
Thank you. Take a look at this PR (https://github.com/econea/nusoap/pull/34). We could start with that.

**Comment by evilangelmd** [comment]
Already begun while i implement all fixes from that PR to my version, i do make changes in code. You can see progress in my forked repo dev.

**Comment by vahidalvandi** [comment]
thank you

**Comment by f3l1x** [comment]
Any progress here https://github.com/econea/nusoap/pull/40 @evilangelmd ?

**Comment by Chris53897** [comment]
Hi. Thank you for this project.
Can you give as some infos about the actual stand of this repository and roadmap?

There are 2 attemps to refactor and modernise it. But they are older. Can you say something about this actual stand?
https://github.com/f00b4r/nusoap/pull/34
https://github.com/f00b4r/nusoap/pull/40

What is the goal to refactor to. Which php version do you wish should be supported?
7.x
7.4 and 8
Only 8

There are other SOAP-Clients here on Github based on ext-soap.
I like to not depend on ext-soap.

My goal would be to make an version that will work with PHP 8 (maybe 7.4), modern and with Namespaces.
I can not gurantee that i have enough time. But i will give my best.

Can you give me some insights about your plans?
